### ISSUE TITLE
reduce composer dependancies

### ISSUE THREAD

**Issue by Desertsnowman** [CalderaWP/caldera-metaplate#15]
This one is a little to composer happy. 
I understand that parts were moved to composer lib for possible pods templates or frontier.

But, at this point this is a different product and when/if it goes into Pods or frontier, that should be a fork or at least inspired by, not the same dependency. Working on stuff is a nightmare
All metaplate-* dependencies should be brought back in keeping only:
* magic-tags
* wp-handlebars-helpers
* handlebars.php

**Comment by Shelob9** [comment]
@Desertsnowman  I disagree. We need metaplate core separately fro two reasons:
1) Frontier 2 needs metaplate-core separate from the templates for the UI.
2) We should encourage developers to pull metaplate core and its dependencies magic-tags/handlebars into their own projects, without our UI to use this as a lightweight templating system. I plan a tutorial on this.

If we fork for Frontier 2 then we have to maintain two identical code bases via copypasta. That's not fun. 

Also, what's a nightmare about working on this? Composer checks out packages as git repos, with the origin set. Just CD into them, make changes and git add/commit/push like any other repo.
