### ISSUE TITLE
Error plugin activation

### ISSUE THREAD

**Issue by yiixii** [CalderaWP/caldera-metaplate#19]
Hi.
I have a problem when try activate the plugin. I get an error: 
```failed to open stream: No such file or directory in ..../wp-content/plugins/caldera-metaplate/vendor/composer/autoload_real.php on line 54    ```

**Comment by Shelob9** [comment]
Are you installing this via WordPress.org, or one of the zip files in the
releases directory or by checking out this repo?

If you checkout this repo or download it using Github's downloader, you
must run composer update, as indicated in the readme.

**Comment by nicolas-san** [comment]
Hello, 
I try today to install this extension directly by the extension manager from my WP admin, and I've the same error,
in fact, in the  wp-content/plugins/caldera-metaplate/vendor there is no autoload_real.php but an autoload.php

**Comment by yiixii** [comment]
Yes. First I try to install via wordpress.org and i've  error . Then I install the zip file, it works without any problems

**Comment by nicolas-san** [comment]
Ok, I've download here the 0.3 zip file, extrtact, and add with ftp the file-locator folder, ard it's ok, I don't know why but the archive on WP must be incomplete or damaged

**Comment by Shelob9** [comment]
This is fixed in the 0.3.1 release on WordPress.org

https://plugins.trac.wordpress.org/browser/caldera-metaplate?rev=1123737
